#!/bin/bash
LINE=""
if [[ $1 = "run" ]]; then
STR="Run to the hills!"
LINE="Run for your life!"
elif [[ $1 = "catarina" ]]; then
STR="Hmm..."
LINE="Quite a pickle indeed."
elif [[ $1 = "world" ]]; then
STR="Sekaaaaaaai de ichiban ohime samaaaa~"
elif [[ $1 = "dna" ]]; then
STR="Keep absolutely still."
LINE="His vision is based on movement."
elif [[ $1 = "scare" ]]; then
STR="Peek a boo!"
elif [[ $1 = "cheers" ]]; then
STR="I think $USER is cute."
LINE="Yeah, you are cute!"
elif [[ $1 = "time" ]]; then
Year=`date +%Y`
Month=`date +%m`
Day=`date +%d`
Hour=`date +%H`
Minute=`date +%M`
Second=`date +%S`
STR="We're the $Day/$Month/$Year and it's $Hour:$Minute:$Second."
LINE="You're welcome."
elif [[ $1 = "speak" ]]; then
STR="Rawr!"
elif [[ $1 = "clear" ]]; then
clear && printf '\e[3J'
STR="Wokety pokety wokety wok~"
LINE="A BRAKA BRAKA BRANACK !!"
elif [[ $1 = "git" ]]; then
if [[ $2 ]]; then
git add .
git commit -m $2
git push
STR="add n' commit n' push!"
LINE="Commit message is: '$2'"
else
STR="Hey what is the message for the commit ?"
LINE="Please ?"
fi
elif [[ $1 = "idle" ]]; then
if [[ $2 = "fast" ]]; then
SLEEP=0.05
else
SLEEP=0.1
fi
TLINES=7
clear && printf '\e[3J'
while true; do
	for f in /Users/cseguier/Documents/scripts/dino_run/*
	do
	tput cup 0 0
	cat $f
	sleep $SLEEP
	done
done
elif [[ $1 = "chill" ]]; then
SLEEP=0.3
TLINES=7
clear && printf '\e[3J'
while true; do
	for f in /Users/cseguier/Documents/scripts/dino_chill/*
	do
	tput cup 0 0
	cat $f
	sleep $SLEEP
	done
done
elif [[ $1 = "bruh" ]]; then
SLEEP=0.3
TLINES=7
clear && printf '\e[3J'
while true; do
	for f in /Users/cseguier/Documents/scripts/dino_bruh/*
	do
	tput cup 0 0
	cat $f
	sleep $SLEEP
	done
done
elif [[ $1 = "bpm" ]]; then
if [[ $2 ]]; then
SLEEP=$(bc <<< "scale=2;(60/$2)-0.01")
else
SLEEP=.43
fi
TLINES=7
clear && printf '\e[3J'
while true; do
	for f in /Users/cseguier/Documents/scripts/dino_nek/*
	do
	tput cup 0 0
	cat $f
	sleep $SLEEP
	done
done
elif [[ $1 = "rule" ]]; then
SLEEP=0.9
TLINES=7
clear && printf '\e[3J'
while true; do
	for f in /Users/cseguier/Documents/scripts/dino_rule/*
	do
	tput cup 0 0
	cat $f
	sleep 1.2
	tput cup 0 0
	cat /Users/cseguier/Documents/scripts/00
	sleep 0.1
	tput cup 0 0
	cat /Users/cseguier/Documents/scripts/01
	sleep 0.5
	tput cup 0 0
	cat /Users/cseguier/Documents/scripts/00
	sleep 0.1
	done
done
elif [[ $1 = "ascii" ]]; then
STR="There you go!"
LINE="... you know man ascii is a thing, right ?"
cat /Users/cseguier/Documents/scripts/dino_various/ascii
elif [[ $1 = "motiv" ]]; then
SLEEP=30
TLINES=7
clear && printf '\e[3J'
while true; do
	for f in /Users/cseguier/Documents/scripts/dino_motiv/*
	do
	tput cup 0 0
	cat $f
	sleep $SLEEP
	tput cup 0 0
	cat /Users/cseguier/Documents/scripts/00
	sleep $SLEEP
	done
done
elif [[ $1 = "poke" ]]; then
cat /Users/cseguier/Documents/scripts/dino_various/poke
exit 0
elif [[ $1 = "math" ]]; then
bc
STR="Yay I like Maths ! Do ALL the CALCULATIONS !"
LINE="... you did good. Dino proud."
elif [[ $1 = "stock" ]]; then
STR="I NEED SPAAAAACE : du -m | sort -n"
LINE="go home, touch .reset_library"
elif [[ $1 = "help" ]]; then
STR="run, catarina, world, dna, scare, cheers, stock, ascii, rule,"
LINE="git, time, speak, clear, idle, math, chill, motiv, bruh, bpm, poke"
else
STR="Hi!"
fi

echo ""
echo "                        ..  "
echo "                      / __)  ${STR}"
echo "               .-^^^-/ /  "
echo "            __/       /   ${LINE}"
echo "           <__.|_|-|_|  \n"
